prompt = """You are a helpful assistant that will give me the key from a description. 
The key and value paris are below: 

Key, Description
P_0.0_0.0,	Mostly straight pointing in right (east) with the shoulder elbow pointing right (east) and the elbow wrist pointing right (east)
P_0.0_22.5,	Mostly straight pointing in right (east) with the shoulder elbow pointing right (east) and the elbow wrist pointing right up (east by north)
P_0.0_45.0,	Slightly bent with the shoulder elbow pointing right (east), elbow wrist pointing up right (northeast)
P_0.0_67.5,	Slightly bent with the shoulder elbow pointing right (east), elbow wrist pointing up right (north by east)
P_0.0_90.0,	Very bent with the shoulder elbow pointing right (east), elbow wrist pointing up (north)
P_0.0_112.5,	Very bent with the shoulder elbow pointing right (east), elbow wrist pointing up left (north by west)
P_0.0_135.0,	Very bent with the shoulder elbow pointing right (east), elbow wrist pointing up left (northwest)
P_0.0_157.5,	Very bent with the shoulder elbow pointing right (east), elbow wrist pointing left up (west by north)
P_0.0_180.0,	Very bent with the shoulder elbow pointing right (east), elbow wrist pointing left (west)
P_0.0_202.5,	Very bent with the shoulder elbow pointing right (east), elbow wrist pointing left down (west by south)
P_0.0_225.0,	Very bent with the shoulder elbow pointing right (east), elbow wrist pointing down left (southwest)
P_0.0_247.5,	Very bent with the shoulder elbow pointing right (east), elbow wrist pointing down left (south by west)
P_0.0_270.0	Very bent with the shoulder elbow pointing right (east), elbow wrist pointing down (south)
P_0.0_292.5	Slightly bent with the shoulder elbow pointing right (east), elbow wrist pointing down right (south by east)
P_0.0_315.0	Slightly bent with the shoulder elbow pointing right (east), elbow wrist pointing down right (southeast)
P_0.0_337.5	Mostly straight pointing in right (east) with the shoulder elbow pointing right (east) and the elbow wrist pointing right down (east by south)
P_22.5_0.0,	Mostly straight pointing in right up (east by north) with the shoulder elbow pointing right up (east by north) and the elbow wrist pointing right (east)
P_22.5_22.5,	Mostly straight pointing in right up (east by north) with the shoulder elbow pointing right up (east by north) and the elbow wrist pointing right up (east by north)
P_22.5_45.0,	Mostly straight pointing in right up (east by north) with the shoulder elbow pointing right up (east by north) and the elbow wrist pointing up right (northeast)
P_22.5_67.5,	Slightly bent with the shoulder elbow pointing right up (east by north), elbow wrist pointing up right (north by east)
P_22.5_90.0,	Slightly bent with the shoulder elbow pointing right up (east by north), elbow wrist pointing up (north)
P_22.5_112.5,	Very bent with the shoulder elbow pointing right up (east by north), elbow wrist pointing up left (north by west)
P_22.5_135.0,	Very bent with the shoulder elbow pointing right up (east by north), elbow wrist pointing up left (northwest)
P_22.5_157.5,	Very bent with the shoulder elbow pointing right up (east by north), elbow wrist pointing left up (west by north)
P_22.5_180.0,	Very bent with the shoulder elbow pointing right up (east by north), elbow wrist pointing left (west)
P_22.5_202.5,	Very bent with the shoulder elbow pointing right up (east by north), elbow wrist pointing left down (west by south)
P_22.5_225.0,	Very bent with the shoulder elbow pointing right up (east by north), elbow wrist pointing down left (southwest)
P_22.5_247.5,	Very bent with the shoulder elbow pointing right up (east by north), elbow wrist pointing down left (south by west)
P_22.5_270.0,	Very bent with the shoulder elbow pointing right up (east by north), elbow wrist pointing down (south)
P_22.5_292.5,	Very bent with the shoulder elbow pointing right up (east by north), elbow wrist pointing down right (south by east)
P_22.5_315.0,	Slightly bent with the shoulder elbow pointing right up (east by north), elbow wrist pointing down right (southeast)
P_22.5_337.5,	Slightly bent with the shoulder elbow pointing right up (east by north), elbow wrist pointing right down (east by south)
P_45.0_0.0,	Slightly bent with the shoulder elbow pointing up right (northeast), elbow wrist pointing right (east)
P_45.0_22.5,	Mostly straight pointing in up right (northeast) with the shoulder elbow pointing up right (northeast) and the elbow wrist pointing right up (east by north)
P_45.0_45.0,	Mostly straight pointing in up right (northeast) with the shoulder elbow pointing up right (northeast) and the elbow wrist pointing up right (northeast)
P_45.0_67.5,	Mostly straight pointing in up right (northeast) with the shoulder elbow pointing up right (northeast) and the elbow wrist pointing up right (north by east)
P_45.0_90.0,	Slightly bent with the shoulder elbow pointing up right (northeast), elbow wrist pointing up (north)
P_45.0_112.5,	Slightly bent with the shoulder elbow pointing up right (northeast), elbow wrist pointing up left (north by west)
P_45.0_135.0,	Very bent with the shoulder elbow pointing up right (northeast), elbow wrist pointing up left (northwest)
P_45.0_157.5,	Very bent with the shoulder elbow pointing up right (northeast), elbow wrist pointing left up (west by north)
P_45.0_180.0,	Very bent with the shoulder elbow pointing up right (northeast), elbow wrist pointing left (west)
P_45.0_202.5,	Very bent with the shoulder elbow pointing up right (northeast), elbow wrist pointing left down (west by south)
P_45.0_225.0,	Very bent with the shoulder elbow pointing up right (northeast), elbow wrist pointing down left (southwest)
P_45.0_247.5,	Very bent with the shoulder elbow pointing up right (northeast), elbow wrist pointing down left (south by west)
P_45.0_270.0,	Very bent with the shoulder elbow pointing up right (northeast), elbow wrist pointing down (south)
P_45.0_292.5,	Very bent with the shoulder elbow pointing up right (northeast), elbow wrist pointing down right (south by east)
P_45.0_315.0,	Very bent with the shoulder elbow pointing up right (northeast), elbow wrist pointing down right (southeast)
P_45.0_337.5,	Slightly bent with the shoulder elbow pointing up right (northeast), elbow wrist pointing right down (east by south)
P_67.5_0.0,	Slightly bent with the shoulder elbow pointing up right (north by east), elbow wrist pointing right (east)
P_67.5_22.5,	Slightly bent with the shoulder elbow pointing up right (north by east), elbow wrist pointing right up (east by north)
P_67.5_45.0,	Mostly straight pointing in up right (north by east) with the shoulder elbow pointing up right (north by east) and the elbow wrist pointing up right (northeast)
P_67.5_67.5,	Mostly straight pointing in up right (north by east) with the shoulder elbow pointing up right (north by east) and the elbow wrist pointing up right (north by east)
P_67.5_90.0,	Mostly straight pointing in up right (north by east) with the shoulder elbow pointing up right (north by east) and the elbow wrist pointing up (north)
P_67.5_112.5,	Slightly bent with the shoulder elbow pointing up right (north by east), elbow wrist pointing up left (north by west)
P_67.5_135.0,	Slightly bent with the shoulder elbow pointing up right (north by east), elbow wrist pointing up left (northwest)
P_67.5_157.5,	Very bent with the shoulder elbow pointing up right (north by east), elbow wrist pointing left up (west by north)
P_67.5_180.0,	Very bent with the shoulder elbow pointing up right (north by east), elbow wrist pointing left (west)
P_67.5_202.5,	Very bent with the shoulder elbow pointing up right (north by east), elbow wrist pointing left down (west by south)
P_67.5_225.0,	Very bent with the shoulder elbow pointing up right (north by east), elbow wrist pointing down left (southwest)
P_67.5_247.5,	Very bent with the shoulder elbow pointing up right (north by east), elbow wrist pointing down left (south by west)
P_67.5_270.0,	Very bent with the shoulder elbow pointing up right (north by east), elbow wrist pointing down (south)
P_67.5_292.5,	Very bent with the shoulder elbow pointing up right (north by east), elbow wrist pointing down right (south by east)
P_67.5_315.0,	Very bent with the shoulder elbow pointing up right (north by east), elbow wrist pointing down right (southeast)
P_67.5_337.5,	Very bent with the shoulder elbow pointing up right (north by east), elbow wrist pointing right down (east by south)
P_90.0_0.0,	Very bent with the shoulder elbow pointing up (north), elbow wrist pointing right (east)
P_90.0_22.5,	Slightly bent with the shoulder elbow pointing up (north), elbow wrist pointing right up (east by north)
P_90.0_45.0,	Slightly bent with the shoulder elbow pointing up (north), elbow wrist pointing up right (northeast)
P_90.0_67.5,	Mostly straight pointing in up (north) with the shoulder elbow pointing up (north) and the elbow wrist pointing up right (north by east)
P_90.0_90.0,	Mostly straight pointing in up (north) with the shoulder elbow pointing up (north) and the elbow wrist pointing up (north)
P_90.0_112.5,	Mostly straight pointing in up (north) with the shoulder elbow pointing up (north) and the elbow wrist pointing up left (north by west)
P_90.0_135.0,	Slightly bent with the shoulder elbow pointing up (north), elbow wrist pointing up left (northwest)
P_90.0_157.5,	Slightly bent with the shoulder elbow pointing up (north), elbow wrist pointing left up (west by north)
P_90.0_180.0,	Very bent with the shoulder elbow pointing up (north), elbow wrist pointing left (west)
P_90.0_202.5,	Very bent with the shoulder elbow pointing up (north), elbow wrist pointing left down (west by south)
P_90.0_225.0,	Very bent with the shoulder elbow pointing up (north), elbow wrist pointing down left (southwest)
P_90.0_247.5,	Very bent with the shoulder elbow pointing up (north), elbow wrist pointing down left (south by west)
P_90.0_270.0,	Very bent with the shoulder elbow pointing up (north), elbow wrist pointing down (south)
P_90.0_292.5,	Very bent with the shoulder elbow pointing up (north), elbow wrist pointing down right (south by east)
P_90.0_315.0,	Very bent with the shoulder elbow pointing up (north), elbow wrist pointing down right (southeast)
P_90.0_337.5,	Very bent with the shoulder elbow pointing up (north), elbow wrist pointing right down (east by south)
P_112.5_0.0,	Very bent with the shoulder elbow pointing up left (north by west), elbow wrist pointing right (east)
P_112.5_22.5,	Very bent with the shoulder elbow pointing up left (north by west), elbow wrist pointing right up (east by north)
P_112.5_45.0,	Slightly bent with the shoulder elbow pointing up left (north by west), elbow wrist pointing up right (northeast)
P_112.5_67.5,	Slightly bent with the shoulder elbow pointing up left (north by west), elbow wrist pointing up right (north by east)
P_112.5_90.0,	Mostly straight pointing in up left (north by west) with the shoulder elbow pointing up left (north by west) and the elbow wrist pointing up (north)
P_112.5_112.5,	Mostly straight pointing in up left (north by west) with the shoulder elbow pointing up left (north by west) and the elbow wrist pointing up left (north by west)
P_112.5_135.0,	Mostly straight pointing in up left (north by west) with the shoulder elbow pointing up left (north by west) and the elbow wrist pointing up left (northwest)
P_112.5_157.5,	Slightly bent with the shoulder elbow pointing up left (north by west), elbow wrist pointing left up (west by north)
P_112.5_180.0,	Slightly bent with the shoulder elbow pointing up left (north by west), elbow wrist pointing left (west)
P_112.5_202.5,	Very bent with the shoulder elbow pointing up left (north by west), elbow wrist pointing left down (west by south)
P_112.5_225.0,	Very bent with the shoulder elbow pointing up left (north by west), elbow wrist pointing down left (southwest)
P_112.5_247.5,	Very bent with the shoulder elbow pointing up left (north by west), elbow wrist pointing down left (south by west)
P_112.5_270.0,	Very bent with the shoulder elbow pointing up left (north by west), elbow wrist pointing down (south)
P_112.5_292.5,	Very bent with the shoulder elbow pointing up left (north by west), elbow wrist pointing down right (south by east)
P_112.5_315.0,	Very bent with the shoulder elbow pointing up left (north by west), elbow wrist pointing down right (southeast)
P_112.5_337.5,	Very bent with the shoulder elbow pointing up left (north by west), elbow wrist pointing right down (east by south)
P_135.0_0.0,	Very bent with the shoulder elbow pointing up left (northwest), elbow wrist pointing right (east)
P_135.0_22.5,	Very bent with the shoulder elbow pointing up left (northwest), elbow wrist pointing right up (east by north)
P_135.0_45.0,	Very bent with the shoulder elbow pointing up left (northwest), elbow wrist pointing up right (northeast)
P_135.0_67.5,	Slightly bent with the shoulder elbow pointing up left (northwest), elbow wrist pointing up right (north by east)
P_135.0_90.0,	Slightly bent with the shoulder elbow pointing up left (northwest), elbow wrist pointing up (north)
P_135.0_112.5,	Mostly straight pointing in up left (northwest) with the shoulder elbow pointing up left (northwest) and the elbow wrist pointing up left (north by west)
P_135.0_135.0,	Mostly straight pointing in up left (northwest) with the shoulder elbow pointing up left (northwest) and the elbow wrist pointing up left (northwest)
P_135.0_157.5,	Mostly straight pointing in up left (northwest) with the shoulder elbow pointing up left (northwest) and the elbow wrist pointing left up (west by north)
P_135.0_180.0,	Slightly bent with the shoulder elbow pointing up left (northwest), elbow wrist pointing left (west)
P_135.0_202.5,	Slightly bent with the shoulder elbow pointing up left (northwest), elbow wrist pointing left down (west by south)
P_135.0_225.0,	Very bent with the shoulder elbow pointing up left (northwest), elbow wrist pointing down left (southwest)
P_135.0_247.5,	Very bent with the shoulder elbow pointing up left (northwest), elbow wrist pointing down left (south by west)
P_135.0_270.0,	Very bent with the shoulder elbow pointing up left (northwest), elbow wrist pointing down (south)
P_135.0_292.5,	Very bent with the shoulder elbow pointing up left (northwest), elbow wrist pointing down right (south by east)
P_135.0_315.0,	Very bent with the shoulder elbow pointing up left (northwest), elbow wrist pointing down right (southeast)
P_135.0_337.5,	Very bent with the shoulder elbow pointing up left (northwest), elbow wrist pointing right down (east by south)
P_157.5_0.0,	Very bent with the shoulder elbow pointing left up (west by north), elbow wrist pointing right (east)
P_157.5_22.5,	Very bent with the shoulder elbow pointing left up (west by north), elbow wrist pointing right up (east by north)
P_157.5_45.0,	Very bent with the shoulder elbow pointing left up (west by north), elbow wrist pointing up right (northeast)
P_157.5_67.5,	Very bent with the shoulder elbow pointing left up (west by north), elbow wrist pointing up right (north by east)
P_157.5_90.0,	Slightly bent with the shoulder elbow pointing left up (west by north), elbow wrist pointing up (north)
P_157.5_112.5,	Slightly bent with the shoulder elbow pointing left up (west by north), elbow wrist pointing up left (north by west)
P_157.5_135.0,	Mostly straight pointing in left up (west by north) with the shoulder elbow pointing left up (west by north) and the elbow wrist pointing up left (northwest)
P_157.5_157.5,	Mostly straight pointing in left up (west by north) with the shoulder elbow pointing left up (west by north) and the elbow wrist pointing left up (west by north)
P_157.5_180.0,	Mostly straight pointing in left up (west by north) with the shoulder elbow pointing left up (west by north) and the elbow wrist pointing left (west)
P_157.5_202.5,	Slightly bent with the shoulder elbow pointing left up (west by north), elbow wrist pointing left down (west by south)
P_157.5_225.0,	Slightly bent with the shoulder elbow pointing left up (west by north), elbow wrist pointing down left (southwest)
P_157.5_247.5,	Very bent with the shoulder elbow pointing left up (west by north), elbow wrist pointing down left (south by west)
P_157.5_270.0,	Very bent with the shoulder elbow pointing left up (west by north), elbow wrist pointing down (south)
P_157.5_292.5,	Very bent with the shoulder elbow pointing left up (west by north), elbow wrist pointing down right (south by east)
P_157.5_315.0,	Very bent with the shoulder elbow pointing left up (west by north), elbow wrist pointing down right (southeast)
P_157.5_337.5,	Very bent with the shoulder elbow pointing left up (west by north), elbow wrist pointing right down (east by south)
P_180.0_0.0,	Very bent with the shoulder elbow pointing left (west), elbow wrist pointing right (east)
P_180.0_22.5,	Very bent with the shoulder elbow pointing left (west), elbow wrist pointing right up (east by north)
P_180.0_45.0,	Very bent with the shoulder elbow pointing left (west), elbow wrist pointing up right (northeast)
P_180.0_67.5,	Very bent with the shoulder elbow pointing left (west), elbow wrist pointing up right (north by east)
P_180.0_90.0,	Very bent with the shoulder elbow pointing left (west), elbow wrist pointing up (north)
P_180.0_112.5,	Slightly bent with the shoulder elbow pointing left (west), elbow wrist pointing up left (north by west)
P_180.0_135.0,	Slightly bent with the shoulder elbow pointing left (west), elbow wrist pointing up left (northwest)
P_180.0_157.5,	Mostly straight pointing in left (west) with the shoulder elbow pointing left (west) and the elbow wrist pointing left up (west by north)
P_180.0_180.0,	Mostly straight pointing in left (west) with the shoulder elbow pointing left (west) and the elbow wrist pointing left (west)
P_180.0_202.5,	Mostly straight pointing in left (west) with the shoulder elbow pointing left (west) and the elbow wrist pointing left down (west by south)
P_180.0_225.0,	Slightly bent with the shoulder elbow pointing left (west), elbow wrist pointing down left (southwest)
P_180.0_247.5,	Slightly bent with the shoulder elbow pointing left (west), elbow wrist pointing down left (south by west)
P_180.0_270.0,	Very bent with the shoulder elbow pointing left (west), elbow wrist pointing down (south)
P_180.0_292.5,	Very bent with the shoulder elbow pointing left (west), elbow wrist pointing down right (south by east)
P_180.0_315.0,	Very bent with the shoulder elbow pointing left (west), elbow wrist pointing down right (southeast)
P_180.0_337.5,	Very bent with the shoulder elbow pointing left (west), elbow wrist pointing right down (east by south)
P_202.5_0.0,	Very bent with the shoulder elbow pointing left down (west by south), elbow wrist pointing right (east)
P_202.5_22.5,	Very bent with the shoulder elbow pointing left down (west by south), elbow wrist pointing right up (east by north)
P_202.5_45.0,	Very bent with the shoulder elbow pointing left down (west by south), elbow wrist pointing up right (northeast)
P_202.5_67.5,	Very bent with the shoulder elbow pointing left down (west by south), elbow wrist pointing up right (north by east)
P_202.5_90.0,	Very bent with the shoulder elbow pointing left down (west by south), elbow wrist pointing up (north)
P_202.5_112.5,	Very bent with the shoulder elbow pointing left down (west by south), elbow wrist pointing up left (north by west)
P_202.5_135.0,	Slightly bent with the shoulder elbow pointing left down (west by south), elbow wrist pointing up left (northwest)
P_202.5_157.5,	Slightly bent with the shoulder elbow pointing left down (west by south), elbow wrist pointing left up (west by north)
P_202.5_180.0,	Mostly straight pointing in left down (west by south) with the shoulder elbow pointing left down (west by south) and the elbow wrist pointing left (west)
P_202.5_202.5,	Mostly straight pointing in left down (west by south) with the shoulder elbow pointing left down (west by south) and the elbow wrist pointing left down (west by south)
P_202.5_225.0,	Mostly straight pointing in left down (west by south) with the shoulder elbow pointing left down (west by south) and the elbow wrist pointing down left (southwest)
P_202.5_247.5,	Slightly bent with the shoulder elbow pointing left down (west by south), elbow wrist pointing down left (south by west)
P_202.5_270.0,	Slightly bent with the shoulder elbow pointing left down (west by south), elbow wrist pointing down (south)
P_202.5_292.5,	Very bent with the shoulder elbow pointing left down (west by south), elbow wrist pointing down right (south by east)
P_202.5_315.0,	Very bent with the shoulder elbow pointing left down (west by south), elbow wrist pointing down right (southeast)
P_202.5_337.5,	Very bent with the shoulder elbow pointing left down (west by south), elbow wrist pointing right down (east by south)
P_225.0_0.0,	Very bent with the shoulder elbow pointing down left (southwest), elbow wrist pointing right (east)
P_225.0_22.5,	Very bent with the shoulder elbow pointing down left (southwest), elbow wrist pointing right up (east by north)
P_225.0_45.0,	Very bent with the shoulder elbow pointing down left (southwest), elbow wrist pointing up right (northeast)
P_225.0_67.5,	Very bent with the shoulder elbow pointing down left (southwest), elbow wrist pointing up right (north by east)
P_225.0_90.0,	Very bent with the shoulder elbow pointing down left (southwest), elbow wrist pointing up (north)
P_225.0_112.5,	Very bent with the shoulder elbow pointing down left (southwest), elbow wrist pointing up left (north by west)
P_225.0_135.0,	Very bent with the shoulder elbow pointing down left (southwest), elbow wrist pointing up left (northwest)
P_225.0_157.5,	Slightly bent with the shoulder elbow pointing down left (southwest), elbow wrist pointing left up (west by north)
P_225.0_180.0,	Slightly bent with the shoulder elbow pointing down left (southwest), elbow wrist pointing left (west)
P_225.0_202.5,	Mostly straight pointing in down left (southwest) with the shoulder elbow pointing down left (southwest) and the elbow wrist pointing left down (west by south)
P_225.0_225.0,	Mostly straight pointing in down left (southwest) with the shoulder elbow pointing down left (southwest) and the elbow wrist pointing down left (southwest)
P_225.0_247.5,	Mostly straight pointing in down left (southwest) with the shoulder elbow pointing down left (southwest) and the elbow wrist pointing down left (south by west)
P_225.0_270.0,	Slightly bent with the shoulder elbow pointing down left (southwest), elbow wrist pointing down (south)
P_225.0_292.5,	Slightly bent with the shoulder elbow pointing down left (southwest), elbow wrist pointing down right (south by east)
P_225.0_315.0,	Very bent with the shoulder elbow pointing down left (southwest), elbow wrist pointing down right (southeast)
P_225.0_337.5,	Very bent with the shoulder elbow pointing down left (southwest), elbow wrist pointing right down (east by south)
P_247.5_0.0,	Very bent with the shoulder elbow pointing down left (south by west), elbow wrist pointing right (east)
P_247.5_22.5,	Very bent with the shoulder elbow pointing down left (south by west), elbow wrist pointing right up (east by north)
P_247.5_45.0,	Very bent with the shoulder elbow pointing down left (south by west), elbow wrist pointing up right (northeast)
P_247.5_67.5,	Very bent with the shoulder elbow pointing down left (south by west), elbow wrist pointing up right (north by east)
P_247.5_90.0,	Very bent with the shoulder elbow pointing down left (south by west), elbow wrist pointing up (north)
P_247.5_112.5,	Very bent with the shoulder elbow pointing down left (south by west), elbow wrist pointing up left (north by west)
P_247.5_135.0,	Very bent with the shoulder elbow pointing down left (south by west), elbow wrist pointing up left (northwest)
P_247.5_157.5,	Very bent with the shoulder elbow pointing down left (south by west), elbow wrist pointing left up (west by north)
P_247.5_180.0,	Slightly bent with the shoulder elbow pointing down left (south by west), elbow wrist pointing left (west)
P_247.5_202.5,	Slightly bent with the shoulder elbow pointing down left (south by west), elbow wrist pointing left down (west by south)
P_247.5_225.0,	Mostly straight pointing in down left (south by west) with the shoulder elbow pointing down left (south by west) and the elbow wrist pointing down left (southwest)
P_247.5_247.5,	Mostly straight pointing in down left (south by west) with the shoulder elbow pointing down left (south by west) and the elbow wrist pointing down left (south by west)
P_247.5_270.0,	Mostly straight pointing in down left (south by west) with the shoulder elbow pointing down left (south by west) and the elbow wrist pointing down (south)
P_247.5_292.5,	Slightly bent with the shoulder elbow pointing down left (south by west), elbow wrist pointing down right (south by east)
P_247.5_315.0,	Slightly bent with the shoulder elbow pointing down left (south by west), elbow wrist pointing down right (southeast)
P_247.5_337.5,	Very bent with the shoulder elbow pointing down left (south by west), elbow wrist pointing right down (east by south)
P_270.0_0.0,	Very bent with the shoulder elbow pointing down (south), elbow wrist pointing right (east)
P_270.0_22.5,	Very bent with the shoulder elbow pointing down (south), elbow wrist pointing right up (east by north)
P_270.0_45.0,	Very bent with the shoulder elbow pointing down (south), elbow wrist pointing up right (northeast)
P_270.0_67.5,	Very bent with the shoulder elbow pointing down (south), elbow wrist pointing up right (north by east)
P_270.0_90.0,	Very bent with the shoulder elbow pointing down (south), elbow wrist pointing up (north)
P_270.0_112.5,	Very bent with the shoulder elbow pointing down (south), elbow wrist pointing up left (north by west)
P_270.0_135.0,	Very bent with the shoulder elbow pointing down (south), elbow wrist pointing up left (northwest)
P_270.0_157.5,	Very bent with the shoulder elbow pointing down (south), elbow wrist pointing left up (west by north)
P_270.0_180.0,	Very bent with the shoulder elbow pointing down (south), elbow wrist pointing left (west)
P_270.0_202.5,	Slightly bent with the shoulder elbow pointing down (south), elbow wrist pointing left down (west by south)
P_270.0_225.0,	Slightly bent with the shoulder elbow pointing down (south), elbow wrist pointing down left (southwest)
P_270.0_247.5,	Mostly straight pointing in down (south) with the shoulder elbow pointing down (south) and the elbow wrist pointing down left (south by west)
P_270.0_270.0,	Mostly straight pointing in down (south) with the shoulder elbow pointing down (south) and the elbow wrist pointing down (south)
P_270.0_292.5,	Mostly straight pointing in down (south) with the shoulder elbow pointing down (south) and the elbow wrist pointing down right (south by east)
P_270.0_315.0,	Slightly bent with the shoulder elbow pointing down (south), elbow wrist pointing down right (southeast)
P_270.0_337.5,	Slightly bent with the shoulder elbow pointing down (south), elbow wrist pointing right down (east by south)
P_292.5_0.0,	Slightly bent with the shoulder elbow pointing down right (south by east), elbow wrist pointing right (east)
P_292.5_22.5,	Very bent with the shoulder elbow pointing down right (south by east), elbow wrist pointing right up (east by north)
P_292.5_45.0,	Very bent with the shoulder elbow pointing down right (south by east), elbow wrist pointing up right (northeast)
P_292.5_67.5,	Very bent with the shoulder elbow pointing down right (south by east), elbow wrist pointing up right (north by east)
P_292.5_90.0,	Very bent with the shoulder elbow pointing down right (south by east), elbow wrist pointing up (north)
P_292.5_112.5,	Very bent with the shoulder elbow pointing down right (south by east), elbow wrist pointing up left (north by west)
P_292.5_135.0,	Very bent with the shoulder elbow pointing down right (south by east), elbow wrist pointing up left (northwest)
P_292.5_157.5,	Very bent with the shoulder elbow pointing down right (south by east), elbow wrist pointing left up (west by north)
P_292.5_180.0,	Very bent with the shoulder elbow pointing down right (south by east), elbow wrist pointing left (west)
P_292.5_202.5,	Very bent with the shoulder elbow pointing down right (south by east), elbow wrist pointing left down (west by south)
P_292.5_225.0,	Slightly bent with the shoulder elbow pointing down right (south by east), elbow wrist pointing down left (southwest)
P_292.5_247.5,	Slightly bent with the shoulder elbow pointing down right (south by east), elbow wrist pointing down left (south by west)
P_292.5_270.0,	Mostly straight pointing in down right (south by east) with the shoulder elbow pointing down right (south by east) and the elbow wrist pointing down (south)
P_292.5_292.5,	Mostly straight pointing in down right (south by east) with the shoulder elbow pointing down right (south by east) and the elbow wrist pointing down right (south by east)
P_292.5_315.0,	Mostly straight pointing in down right (south by east) with the shoulder elbow pointing down right (south by east) and the elbow wrist pointing down right (southeast)
P_292.5_337.5,	Slightly bent with the shoulder elbow pointing down right (south by east), elbow wrist pointing right down (east by south)
P_315.0_0.0,	Slightly bent with the shoulder elbow pointing down right (southeast), elbow wrist pointing right (east)
P_315.0_22.5,	Slightly bent with the shoulder elbow pointing down right (southeast), elbow wrist pointing right up (east by north)
P_315.0_45.0,	Very bent with the shoulder elbow pointing down right (southeast), elbow wrist pointing up right (northeast)
P_315.0_67.5,	Very bent with the shoulder elbow pointing down right (southeast), elbow wrist pointing up right (north by east)
P_315.0_90.0,	Very bent with the shoulder elbow pointing down right (southeast), elbow wrist pointing up (north)
P_315.0_112.5,	Very bent with the shoulder elbow pointing down right (southeast), elbow wrist pointing up left (north by west)
P_315.0_135.0,	Very bent with the shoulder elbow pointing down right (southeast), elbow wrist pointing up left (northwest)
P_315.0_157.5,	Very bent with the shoulder elbow pointing down right (southeast), elbow wrist pointing left up (west by north)
P_315.0_180.0,	Very bent with the shoulder elbow pointing down right (southeast), elbow wrist pointing left (west)
P_315.0_202.5,	Very bent with the shoulder elbow pointing down right (southeast), elbow wrist pointing left down (west by south)
P_315.0_225.0,	Very bent with the shoulder elbow pointing down right (southeast), elbow wrist pointing down left (southwest)
P_315.0_247.5,	Slightly bent with the shoulder elbow pointing down right (southeast), elbow wrist pointing down left (south by west)
P_315.0_270.0,	Slightly bent with the shoulder elbow pointing down right (southeast), elbow wrist pointing down (south)
P_315.0_292.5,	Mostly straight pointing in down right (southeast) with the shoulder elbow pointing down right (southeast) and the elbow wrist pointing down right (south by east)
P_315.0_315.0,	Mostly straight pointing in down right (southeast) with the shoulder elbow pointing down right (southeast) and the elbow wrist pointing down right (southeast)
P_315.0_337.5,	Mostly straight pointing in down right (southeast) with the shoulder elbow pointing down right (southeast) and the elbow wrist pointing right down (east by south)
P_337.5_0.0,	Mostly straight pointing in right down (east by south) with the shoulder elbow pointing right down (east by south) and the elbow wrist pointing right (east)
P_337.5_22.5,	Slightly bent with the shoulder elbow pointing right down (east by south), elbow wrist pointing right up (east by north)
P_337.5_45.0,	Slightly bent with the shoulder elbow pointing right down (east by south), elbow wrist pointing up right (northeast)
P_337.5_67.5,	Very bent with the shoulder elbow pointing right down (east by south), elbow wrist pointing up right (north by east)
P_337.5_90.0,	Very bent with the shoulder elbow pointing right down (east by south), elbow wrist pointing up (north)
P_337.5_112.5,	Very bent with the shoulder elbow pointing right down (east by south), elbow wrist pointing up left (north by west)
P_337.5_135.0,	Very bent with the shoulder elbow pointing right down (east by south), elbow wrist pointing up left (northwest)
P_337.5_157.5,	Very bent with the shoulder elbow pointing right down (east by south), elbow wrist pointing left up (west by north)
P_337.5_180.0,	Very bent with the shoulder elbow pointing right down (east by south), elbow wrist pointing left (west)
P_337.5_202.5,	Very bent with the shoulder elbow pointing right down (east by south), elbow wrist pointing left down (west by south)
P_337.5_225.0,	Very bent with the shoulder elbow pointing right down (east by south), elbow wrist pointing down left (southwest)
P_337.5_247.5,	Very bent with the shoulder elbow pointing right down (east by south), elbow wrist pointing down left (south by west)
P_337.5_270.0,	Slightly bent with the shoulder elbow pointing right down (east by south), elbow wrist pointing down (south)
P_337.5_292.5,	Slightly bent with the shoulder elbow pointing right down (east by south), elbow wrist pointing down right (south by east)
P_337.5_315.0,	Mostly straight pointing in right down (east by south) with the shoulder elbow pointing right down (east by south) and the elbow wrist pointing down right (southeast)
P_337.5_337.5,	Mostly straight pointing in right down (east by south) with the shoulder elbow pointing right down (east by south) and the elbow wrist pointing right down (east by south)


What key correspionds to the following description:
Very bent with the shoulder elbow pointing down (south), elbow wrist pointing up right (north by east)
"""


    
